version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://user:pass@db:5432/testdb
    volumes:
      - ./artifacts:/app/artifacts
      - ./reports:/app/reports
    depends_on:
      - redis
      - db
    networks:
      - test-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - test-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  postgres_data: